#include "../inc/parser.hpp"
#include <unordered_map>

const std::unordered_map<std::string, TokenPtr(*)(Origin origin)> KEYWORDS {

    { "nop", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::NOP, origin); } },
    { "add", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::ADD, origin); } },
    { "adc", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::ADC, origin); } },
    { "sub", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::SUB, origin); } },
    { "sbc", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::SBC, origin); } },
    { "cmp", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::CMP, origin); } },
    { "cmc", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::CMC, origin); } },
    { "and", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::AND, origin); } },
    { "or", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::OR, origin); } },
    { "xor", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::XOR, origin); } },
    { "shl", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::SHL, origin); } },
    { "shr", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::SHR, origin); } },
    { "asr", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::ASR, origin); } },
    { "mov", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::MOV, origin); } },
    { "mvh", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::MVH, origin); } },
    { "jmp", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::JMP, origin); } },
    { "rjmp", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::RJMP, origin); } },
    { "jbl", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::JBL, origin); } },
    { "jbh", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::JBH, origin); } },
    { "call", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::CALL, origin); } },
    { "rcall", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::RCALL, origin); } },
    { "cbl", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::CBL, origin); } },
    { "cbh", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::CBH, origin); } },
    { "ret", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::RET, origin); } },
    { "retcall", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::CALLRET, origin); } },
    { "ld", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::LD, origin); } },
    { "ldr", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::LDR, origin); } },
    { "lds", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::LDS, origin); } },
    { "ldf", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::LDF, origin); } },
    { "st", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::ST, origin); } },
    { "sts", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::STS, origin); } },
    { "stf", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::STF, origin); } },
    { "*mov", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::P_MOV, origin); } },
    { "*jmp", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::P_JMP, origin); } },
    { "*call", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::P_CALL, origin); } },
    { "*push", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::P_PUSH, origin); } },
    { "*pop", [] (Origin origin) -> TokenPtr { return std::make_unique<Opcode>(Opcode::Value::P_POP, origin); } },

    { "c", [] (Origin origin) -> TokenPtr { return std::make_unique<Condition>(JumpCond::C, false, origin); } },
    { "gteu", [] (Origin origin) -> TokenPtr { return std::make_unique<Condition>(JumpCond::C, false, origin); } },
    { "v", [] (Origin origin) -> TokenPtr { return std::make_unique<Condition>(JumpCond::V, false, origin); } },
    { "n", [] (Origin origin) -> TokenPtr { return std::make_unique<Condition>(JumpCond::N, false, origin); } },
    { "z", [] (Origin origin) -> TokenPtr { return std::make_unique<Condition>(JumpCond::Z, false, origin); } },
    { "eq", [] (Origin origin) -> TokenPtr { return std::make_unique<Condition>(JumpCond::Z, false, origin); } },
    { "gt", [] (Origin origin) -> TokenPtr { return std::make_unique<Condition>(JumpCond::G, false, origin); } },
    { "gte", [] (Origin origin) -> TokenPtr { return std::make_unique<Condition>(JumpCond::GE, false, origin); } },
    { "gtu", [] (Origin origin) -> TokenPtr { return std::make_unique<Condition>(JumpCond::GU, false, origin); } },
    { "nc", [] (Origin origin) -> TokenPtr { return std::make_unique<Condition>(JumpCond::C, true, origin); } },
    { "ltu", [] (Origin origin) -> TokenPtr { return std::make_unique<Condition>(JumpCond::C, true, origin); } },
    { "nv", [] (Origin origin) -> TokenPtr { return std::make_unique<Condition>(JumpCond::V, true, origin); } },
    { "nn", [] (Origin origin) -> TokenPtr { return std::make_unique<Condition>(JumpCond::N, true, origin); } },
    { "nz", [] (Origin origin) -> TokenPtr { return std::make_unique<Condition>(JumpCond::Z, true, origin); } },
    { "ne", [] (Origin origin) -> TokenPtr { return std::make_unique<Condition>(JumpCond::Z, true, origin); } },
    { "lte", [] (Origin origin) -> TokenPtr { return std::make_unique<Condition>(JumpCond::G, true, origin); } },
    { "lt", [] (Origin origin) -> TokenPtr { return std::make_unique<Condition>(JumpCond::GE, true, origin); } },
    { "lteu", [] (Origin origin) -> TokenPtr { return std::make_unique<Condition>(JumpCond::GU, true, origin); } },

    { "ra.l", [] (Origin origin) -> TokenPtr { return std::make_unique<DataRegisterArg>(Register::RA_L, origin); } },
    { "ra.h", [] (Origin origin) -> TokenPtr { return std::make_unique<DataRegisterArg>(Register::RA_H, origin); } },
    { "sr", [] (Origin origin) -> TokenPtr { return std::make_unique<DataRegisterArg>(Register::SR, origin); } },
    { "sp", [] (Origin origin) -> TokenPtr { return std::make_unique<DataRegisterArg>(Register::SP, origin); } },
    { "ga", [] (Origin origin) -> TokenPtr { return std::make_unique<DataRegisterArg>(Register::GA, origin); } },
    { "fp", [] (Origin origin) -> TokenPtr { return std::make_unique<DataRegisterArg>(Register::GA, origin); } },
    { "gb", [] (Origin origin) -> TokenPtr { return std::make_unique<DataRegisterArg>(Register::GB, origin); } },
    { "gc", [] (Origin origin) -> TokenPtr { return std::make_unique<DataRegisterArg>(Register::GC, origin); } },
    { "gd", [] (Origin origin) -> TokenPtr { return std::make_unique<DataRegisterArg>(Register::GD, origin); } },
    { "ge.l", [] (Origin origin) -> TokenPtr { return std::make_unique<DataRegisterArg>(Register::GE_L, origin); } },
    { "ge.h", [] (Origin origin) -> TokenPtr { return std::make_unique<DataRegisterArg>(Register::GE_H, origin); } },
    { "gf.l", [] (Origin origin) -> TokenPtr { return std::make_unique<DataRegisterArg>(Register::GF_L, origin); } },
    { "gf.h", [] (Origin origin) -> TokenPtr { return std::make_unique<DataRegisterArg>(Register::GF_H, origin); } },
    { "gg.l", [] (Origin origin) -> TokenPtr { return std::make_unique<DataRegisterArg>(Register::GG_L, origin); } },
    { "gg.h", [] (Origin origin) -> TokenPtr { return std::make_unique<DataRegisterArg>(Register::GG_H, origin); } },
    { "gh.l", [] (Origin origin) -> TokenPtr { return std::make_unique<DataRegisterArg>(Register::GH_L, origin); } },
    { "gh.h", [] (Origin origin) -> TokenPtr { return std::make_unique<DataRegisterArg>(Register::GH_H, origin); } },

    { "ra", [] (Origin origin) -> TokenPtr { return std::make_unique<WideRegisterArg>(WideRegisterArg::Value::RA, origin); } },
    { "ge", [] (Origin origin) -> TokenPtr { return std::make_unique<WideRegisterArg>(WideRegisterArg::Value::GE, origin); } },
    { "gf", [] (Origin origin) -> TokenPtr { return std::make_unique<WideRegisterArg>(WideRegisterArg::Value::GF, origin); } },
    { "gg", [] (Origin origin) -> TokenPtr { return std::make_unique<WideRegisterArg>(WideRegisterArg::Value::GG, origin); } },
    { "gh", [] (Origin origin) -> TokenPtr { return std::make_unique<WideRegisterArg>(WideRegisterArg::Value::GH, origin); } },

    { ".move", [] (Origin origin) -> TokenPtr { return std::make_unique<Directive>(Directive::Value::MOVE, origin); } },
    { ".byte", [] (Origin origin) -> TokenPtr { return std::make_unique<Directive>(Directive::Value::BYTE, origin); } },
    { ".bytes", [] (Origin origin) -> TokenPtr { return std::make_unique<Directive>(Directive::Value::BYTES, origin); } },
};