#include "../inc/parser.hpp"
#include <unordered_map>

const std::unordered_map<std::string, TokenPtr(*)(size_t line)> KEYWORDS {

    { "nop", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::NOP); } },
    { "add", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::ADD); } },
    { "adc", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::ADC); } },
    { "sub", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::SUB); } },
    { "sbc", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::SBC); } },
    { "cmp", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::CMP); } },
    { "cmc", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::CMC); } },
    { "and", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::AND); } },
    { "or", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::OR); } },
    { "xor", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::XOR); } },
    { "shl", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::SHL); } },
    { "shr", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::SHR); } },
    { "mov", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::MOV); } },
    { "mvh", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::MVH); } },
    { "jmp", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::JMP); } },
    { "rjmp", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::RJMP); } },
    { "jbl", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::JBL); } },
    { "jbh", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::JBH); } },
    { "call", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::CALL); } },
    { "rcall", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::RCALL); } },
    { "cbl", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::CBL); } },
    { "cbh", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::CBH); } },
    { "ret", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::RET); } },
    { "retcall", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::CALLRET); } },
    { "ld", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::LD); } },
    { "ldr", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::LDR); } },
    { "lds", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::LDS); } },
    { "ldf", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::LDF); } },
    { "st", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::ST); } },
    { "sts", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::STS); } },
    { "stf", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::STF); } },
    { "push", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::PUSH); } },
    { "pop", [] (size_t line) -> TokenPtr { return std::make_unique<Opcode>(line, Opcode::Value::POP); } },

    { "c", [] (size_t line) -> TokenPtr { return std::make_unique<Condition>(line, JumpCond::C, false); } },
    { "gteu", [] (size_t line) -> TokenPtr { return std::make_unique<Condition>(line, JumpCond::C, false); } },
    { "v", [] (size_t line) -> TokenPtr { return std::make_unique<Condition>(line, JumpCond::V, false); } },
    { "n", [] (size_t line) -> TokenPtr { return std::make_unique<Condition>(line, JumpCond::N, false); } },
    { "z", [] (size_t line) -> TokenPtr { return std::make_unique<Condition>(line, JumpCond::Z, false); } },
    { "eq", [] (size_t line) -> TokenPtr { return std::make_unique<Condition>(line, JumpCond::Z, false); } },
    { "gt", [] (size_t line) -> TokenPtr { return std::make_unique<Condition>(line, JumpCond::G, false); } },
    { "gte", [] (size_t line) -> TokenPtr { return std::make_unique<Condition>(line ,JumpCond::GE, false); } },
    { "gtu", [] (size_t line) -> TokenPtr { return std::make_unique<Condition>(line ,JumpCond::GU, false); } },
    { "nc", [] (size_t line) -> TokenPtr { return std::make_unique<Condition>(line, JumpCond::C, true); } },
    { "ltu", [] (size_t line) -> TokenPtr { return std::make_unique<Condition>(line, JumpCond::C, true); } },
    { "nv", [] (size_t line) -> TokenPtr { return std::make_unique<Condition>(line, JumpCond::V, true); } },
    { "nn", [] (size_t line) -> TokenPtr { return std::make_unique<Condition>(line, JumpCond::N, true); } },
    { "nz", [] (size_t line) -> TokenPtr { return std::make_unique<Condition>(line, JumpCond::Z, true); } },
    { "ne", [] (size_t line) -> TokenPtr { return std::make_unique<Condition>(line, JumpCond::Z, true); } },
    { "lte", [] (size_t line) -> TokenPtr { return std::make_unique<Condition>(line, JumpCond::G, true); } },
    { "lt", [] (size_t line) -> TokenPtr { return std::make_unique<Condition>(line, JumpCond::GE, true); } },
    { "lteu", [] (size_t line) -> TokenPtr { return std::make_unique<Condition>(line, JumpCond::GU, true); } },

    { "ra.l", [] (size_t line) -> TokenPtr { return std::make_unique<DataRegisterArg>(line, Register::RA_L); } },
    { "ra.h", [] (size_t line) -> TokenPtr { return std::make_unique<DataRegisterArg>(line, Register::RA_H); } },
    { "sr", [] (size_t line) -> TokenPtr { return std::make_unique<DataRegisterArg>(line, Register::SR); } },
    { "sp", [] (size_t line) -> TokenPtr { return std::make_unique<DataRegisterArg>(line, Register::SP); } },
    { "ga", [] (size_t line) -> TokenPtr { return std::make_unique<DataRegisterArg>(line, Register::GA); } },
    { "fp", [] (size_t line) -> TokenPtr { return std::make_unique<DataRegisterArg>(line, Register::GA); } },
    { "gb", [] (size_t line) -> TokenPtr { return std::make_unique<DataRegisterArg>(line, Register::GB); } },
    { "gc", [] (size_t line) -> TokenPtr { return std::make_unique<DataRegisterArg>(line, Register::GC); } },
    { "gd", [] (size_t line) -> TokenPtr { return std::make_unique<DataRegisterArg>(line, Register::GD); } },
    { "ge.l", [] (size_t line) -> TokenPtr { return std::make_unique<DataRegisterArg>(line, Register::GE_L); } },
    { "ge.h", [] (size_t line) -> TokenPtr { return std::make_unique<DataRegisterArg>(line, Register::GE_H); } },
    { "gf.l", [] (size_t line) -> TokenPtr { return std::make_unique<DataRegisterArg>(line, Register::GF_L); } },
    { "gf.h", [] (size_t line) -> TokenPtr { return std::make_unique<DataRegisterArg>(line, Register::GF_H); } },
    { "gg.l", [] (size_t line) -> TokenPtr { return std::make_unique<DataRegisterArg>(line, Register::GG_L); } },
    { "gg.h", [] (size_t line) -> TokenPtr { return std::make_unique<DataRegisterArg>(line, Register::GG_H); } },
    { "gh.l", [] (size_t line) -> TokenPtr { return std::make_unique<DataRegisterArg>(line, Register::GH_L); } },
    { "gh.h", [] (size_t line) -> TokenPtr { return std::make_unique<DataRegisterArg>(line, Register::GH_H); } },

    { "ra", [] (size_t line) -> TokenPtr { return std::make_unique<WideRegisterArg>(line, WideRegisterArg::Value::RA); } },
    { "ge", [] (size_t line) -> TokenPtr { return std::make_unique<WideRegisterArg>(line, WideRegisterArg::Value::GE); } },
    { "gf", [] (size_t line) -> TokenPtr { return std::make_unique<WideRegisterArg>(line, WideRegisterArg::Value::GF); } },
    { "gg", [] (size_t line) -> TokenPtr { return std::make_unique<WideRegisterArg>(line, WideRegisterArg::Value::GG); } },
    { "gh", [] (size_t line) -> TokenPtr { return std::make_unique<WideRegisterArg>(line, WideRegisterArg::Value::GH); } },

    { ".move", [] (size_t line) -> TokenPtr { return std::make_unique<Directive>(line, Directive::Value::MOVE); } },
    { ".byte", [] (size_t line) -> TokenPtr { return std::make_unique<Directive>(line, Directive::Value::BYTE); } },
    { ".bytes", [] (size_t line) -> TokenPtr { return std::make_unique<Directive>(line, Directive::Value::BYTES); } },
};